destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/spotlightenterprise-pdf"
port: 4010
output: pdf
product: SpotlightEnterprise
print_title: Spotlight Enterprise — PDF product
print_subtitle: Version 12.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true